### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by saraeygholamreza** [sameera-madushan/SubtitleBOX#1]
hey,
I got this problem. 
take a look at it, pls.
![image](https://user-images.githubusercontent.com/49529058/79225056-68084c80-7e71-11ea-90f1-9ca04df33d73.png)

**Comment by TheoCoombes** [comment]
You're missing the python module 'wheel'

**Comment by sameera-madushan** [comment]
[python -m pip install wheel setuptools](https://stackoverflow.com/a/58944293/13276219)

**Comment by saraeygholamreza** [comment]
didn't work, yet!

**Comment by sameera-madushan** [comment]
Try pip3 install pythonnet

**Comment by saraeygholamreza** [comment]
I did,
but still, there is a problem. 
I try to figure out it later. 
thanks

**Comment by DarkCeptor44** [comment]
@saraeygholamreza Try the `--user` option, it helped me before: `pip install -r requirements.txt --user`.

**Comment by MidnightsWar** [comment]
@sameera-madushan I was having the same error.  When running python 8 I was getting an error with pythonnet.  I downgraded to python 7 and it is running flawlessly now.
