### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by Gahamelas** [sameera-madushan/SubtitleBOX#14]
Hi, 

I am running this:

python sbox.py

`python sbox.py movie.mkv -lang en `

and get this error:

```
usage: sbox.py [-h] [-f FILE_PATH] [-lang LANGUAGE_CODE]
sbox.py: error: unrecognized arguments: movie.mkv -lang en
```

I have tried using quotes, in vain. Also tried without the -lang argument. In vain.
Any help welcome thanks!

**Comment by sameera-madushan** [comment]
You are missing the -f flag before the movie file path.

**Comment by Gahamelas** [comment]
Oh dear. So silly of me. Thank you.
Can it handle several movie files at once? Thanks.

**Comment by sameera-madushan** [comment]
No it does not handle several movie files at once. if you want to get subtitles for entire directory containing movies check issue #4
